(load-file "~/.emacs.d/core/package_manager.el")

(load-file "~/.emacs.d/client/redunt.el")
(load-file "~/.emacs.d/client/dashboard.el")
(load-file "~/.emacs.d/client/confirmation.el")
(load-file "~/.emacs.d/client/encoding.el")

(load-file "~/.emacs.d/packages/gcmh.el")
(load-file "~/.emacs.d/packages/emacs.el")
(load-file "~/.emacs.d/packages/general.el")
(load-file "~/.emacs.d/packages/evil.el")
(load-file "~/.emacs.d/packages/evil_collection.el")
(load-file "~/.emacs.d/packages/diff_hl.el")
(load-file "~/.emacs.d/packages/which_key.el")
(load-file "~/.emacs.d/packages/ivy.el")
(load-file "~/.emacs.d/packages/magit.el")
(load-file "~/.emacs.d/packages/projectile.el")
(load-file "~/.emacs.d/packages/doom_themes.el")
(load-file "~/.emacs.d/packages/nyan_mode.el")
(load-file "~/.emacs.d/packages/commentary.el")
(load-file "~/.emacs.d/packages/vterm/vterm.el")
(load-file "~/.emacs.d/packages/vterm/vterm_toggle.el")
